[package]
name = "saytoma"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["canvas", "image", "advanced", "tokio"]}
zip = "0.6"
tempfile = "3.8"
natord = "1.0.9"
tokio = { version = "1.47.1", features = ["sync"] }
iced_native = "0.10.3"
rfd = "0.15.4"
